#!/usr/bin/env bash

set -e

export DOTFILES="$PWD"

# run install scripts
for install_file in **/install.sh; do
  echo ""
  echo "\033[00;32m──›\033[0m Installing $install_file"
  echo ""
  
  bash -e $install_file
done

# run up function
./bin/up
