#!/usr/bin/env bash

set -e

export DOTFILES="$PWD"

# clean broken symlinks
find ~ -xtype l -exec rm -f {} \;

# run install scripts
for install_file in **/install.sh; do
  bash -e $install_file
done

# run up function
./bin/up
