export PYTHONUSERBASE=$HOME/.local/python
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Code
export VIRTUALENVWRAPPER_SCRIPT=$PYTHONUSERBASE/bin/virtualenvwrapper.sh
export VIRTUAL_ENV_DISABLE_PROMPT=1
export PATH=$PYTHONUSERBASE/bin:$PATH
